28 crud de item
BrunoRRamos/Divide.ae pull request #38
Opened 2024-09-10 21:39 UTC by ianzx15

2024-09-10 23:49 UTC, PedroCost4 requested changes

2024-09-10 23:49 UTC, PedroCost4 commented on packages/api/src/models/bill/bill.ts
> +import { createTRPCRouter } from "../../trpc";
Issue: O nome do arquivo é melhor que seja nomeado `router.ts` pq ja esta dentro do module de bill

2024-09-10 23:49 UTC, PedroCost4 commented on packages/api/src/models/bill/__tests__/billSuite.spec.ts
> +import { beforeAll, expect, it } from "vitest";
Issue: Acho melhor separar em testes para cada methodo
ex: 
`create.spec.ts` `delete.spec.ts`

2024-09-10 23:54 UTC, PedroCost4 submitted a review, later dismissed

2024-09-10 23:54 UTC, PedroCost4 commented on packages/api/src/models/bill/controllers/delete.ts
> +        return ctx.db.bill.delete({ where: { id: input } });
é importante checar se a bill existe antes de tentar deletar, o prisma pode fazer um delete sem where nesse caso

2024-09-10 23:54 UTC, PedroCost4 commented on packages/api/src/models/bill/controllers/update.ts
> +      throw new Error("Bill not found");
Existe um erro próprio do trpc para dar throw nas procedures
```ts
throw new TRPCError({
    code: "NOT_FOUND",
    message: "Bill not found"
})
```

2024-09-10 23:54 UTC, PedroCost4 commented on packages/api/src/models/bill/__tests__/billSuite.spec.ts
> +  expect(bills.length).toBeGreaterThanOrEqual(2);
É melhor testar com equals(2), pra saber que existem realmente só as duas adicionadas

2024-09-10 23:54 UTC, PedroCost4 commented on packages/api/src/models/bill/controllers/get.ts
> +    .input(z.object({ id: z.string() }))
como é só um metodo simples, podemos apenas colocar 
```ts
.input(z.string())
```

2024-09-11 23:21 UTC, gabrielmeloc22 commented on packages/api/src/models/bill/__tests__/update.spec.ts
> +    groupId: "",
n deveria poder fazer o update colocando o groupId como uma string vazia

2024-09-11 23:24 UTC, gabrielmeloc22 commented on packages/api/src/models/bill/controllers/create.ts
> +    return ctx.db.bill.create({ data: input });
precisa checar se o grupo existe, uma conta é de um grupo

2024-09-11 23:26 UTC, gabrielmeloc22 commented on packages/api/src/models/bill/controllers/get.ts
> +  return ctx.db.bill.findMany();
a gente provavelmente vai pegar as contas de um grupo, entao precisamos filtrar por grupo aqui

2024-09-11 23:26 UTC, gabrielmeloc22 commented on packages/api/src/models/bill/controllers/get.ts
> +  return ctx.db.bill.findMany();
pensa que vamos ter a tela dentro do grupo, e ai vai aparecer todas as contas dentro daquele grupo

2024-09-11 23:30 UTC, gabrielmeloc22 commented on packages/api/src/models/bill/__tests__/update.spec.ts
> +it("should update a bill", async () => {
checar permissao do usuario

2024-09-11 23:31 UTC, gabrielmeloc22 commented on packages/api/src/models/bill/__tests__/get.spec.ts
> +it("should get a created bill", async () => {
checar se o usuario pertence ao grupo antes de fazer qualquer operacao, create, delete, update, get

2024-09-11 23:33 UTC, gabrielmeloc22 commented on packages/api/src/models/bill/__tests__/get.spec.ts
> +it("should get a created bill", async () => {
pode criar uma funcao utilitaria pra checar isso e reutilizar em todas as procedures

2024-09-11 23:34 UTC, gabrielmeloc22 commented on packages/api/src/models/bill/__tests__/get.spec.ts
> +it("should get a created bill", async () => {
deixa em um arquivo separado de permissoes

2024-09-17 00:05 UTC, gabrielmeloc22 approved these changes

2024-09-17 00:06 UTC, merged